### ISSUE TITLE
FEAT : HEADER SECTION RESPONSIVE

### ISSUE THREAD

**Issue by AbhinaySngh** [Harshdev098/Research-Nexas#10]
![image](https://github.com/user-attachments/assets/a516478e-094b-4e63-818b-e17ed0e903ea)

**Comment by AbhinaySngh** [comment]
@Harshdev098 Please assign me this issue under GSSOC-EXT label.

**Comment by Harshdev098** [comment]
Sure @AbhinaySngh , Please go ahead! Assigned

**Comment by NEGRAH-S** [comment]
@AbhinaySngh, I am one of mentor for this repo, do u want this issue to be counted as hacktober contribution? If yes, i will add the tag for same

**Comment by AbhinaySngh** [comment]
@NEGRAH-S Yes please.

**Comment by Harshdev098** [comment]
This issue have been solved
