### ISSUE TITLE
Implement Signup Using Trusted Email Services

### ISSUE THREAD

**Issue by smog-root** [Harshdev098/Research-Nexas#101]
Revise the current signup and login process to include email domain validation. Limit signups and login to users with email addresses from reputable providers (e.g., Gmail, Outlook).

During the signup process, extract the domain from the user's email address and compare it against a predefined list of trusted providers. If there is a match, allow the signup to proceed; if not, display an error message.

i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!

@Harshdev098

**Comment by omkumar312** [comment]
I want to work on this issue, please assign me this issue.

**Comment by smog-root** [comment]
@omkumar312 i'm working on it. i don't need any assistance!!
