### ISSUE TITLE
[Security] Password need to meet minimum requirements for signup

### ISSUE THREAD

**Issue by smog-root** [Harshdev098/Research-Nexas#113]
i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!

**Password Requirements:**

At least 8 characters long.
At least 1 uppercase letter (A-Z).
At least 1 lowercase letter (a-z).
At least 1 number (0-9).
At least 1 special character (e.g., !@#$%^&*()).

Now, when a user tries to register, they will receive immediate feedback if their password does not meet these criteria. Let me know if you need any further changes or additional features!

**_i have already done the task_**:

**signup.html**

![signup.html](https://github.com/user-attachments/assets/7e8ab818-8f46-4268-89bd-1eef7ecb5a3e)

i'm wait for you to assign!

**Comment by Harshdev098** [comment]
Just add it for both stakeholders and faculty authentication also

**Comment by smog-root** [comment]
Hoo shit! I commited. I added only for sigup.

I will add to stk_signup.html in another PR!!

**Comment by smog-root** [comment]
When are you going to merge my PR's? #115 #114
