### ISSUE TITLE
Documentation update required: Error while using the myql client npm package

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#133]
**Description:**
When trying to run the server using `nodemon dbServer.js`, an error occurs: `Client does not support authentication protocol requested by server; consider upgrading MySQL client`.

**Solution:**
Resetting your password will solve this problem. Appropriate documentation changes are required for that.

 @Harshdev098 *Please assign this issue to me and add `hacktoberfest` and `gssoc-ext` labels to it.*

**Comment by Harshdev098** [comment]
Its not only issue of resetting a password or giving right password in .env file, its necessary to shift the mysql to latest versions or mysql2

**Comment by trinetra110** [comment]
> Its not only issue of resetting a password or giving right password in .env file, its necessary to shift the mysql to latest versions or mysql2

Yes that's true, As of now, updating mysql to mysql2 requires a lot of changes so I'll update the documentation for temporary solution for this problem. Later, I'll try to modify mysql to mysql2.
