### ISSUE TITLE
VIsibility of showing papers while approval

### ISSUE THREAD

**Issue by Harshdev098** [Harshdev098/Research-Nexas#134]
The paper details are showing on the top of the page, user have to scroll up the page to see the papers for approval. Fixing its visibility so that its easy to see the paper details is necessary

![image](https://github.com/user-attachments/assets/997140bb-800a-4907-b9b0-ae53168b35a3)

**Comment by trinetra110** [comment]
@Harshdev098 please assign me this issue.
