### ISSUE TITLE
Visibility of showing papers while allotment

### ISSUE THREAD

**Issue by Harshdev098** [Harshdev098/Research-Nexas#135]
The paper details are showing on the top of the page, user have to scroll up the page to see the papers for allotment. Fixing its visibility so that its easy to see the paper details is necessary

![image](https://github.com/user-attachments/assets/0686ab32-b60e-415b-a7a6-5447e7e58b29)

**Comment by ygowthamr** [comment]
@Harshdev098 
Assign me this issue i will try to solve.
