### ISSUE TITLE
File_Upload_Size_Limit_Exceeded

### ISSUE THREAD

**Issue by smog-root** [Harshdev098/Research-Nexas#147]
I'm experiencing an issue with file uploads exceeding the maximum size limit set by the repository. This is causing problems when attempting to upload necessary files.

**Details:**

- Current Maximum Upload Size: [insert size limit, e.g., 100 MB]
- Files Causing Issues: [list the files and their 
- Error Message: [insert any relevant error messages encountered during upload]
- Expected Behavior: I expect to be able to upload files larger than the current limit without any issues.

**Note:** i'm expecting a gssoc-ext with level3 and a hacktoberfest-accepted label!

@Harshdev098

**Comment by Harshdev098** [comment]
Are you talking about the paper uploadation feature in the project or what

**Comment by smog-root** [comment]
Yaa. The this which deals with file_upload.html!!

**Comment by Harshdev098** [comment]
But I think not any of the research paper size can exceed above 100MB

**Comment by smog-root** [comment]
But. Any one can DDOS the feature! So settin up a rate limit for it is not a bad idea!

**Comment by smog-root** [comment]
Any one with a basic  script can automate uploads!

**Comment by Harshdev098** [comment]
Are you talking about increasing the size limit or what can you explain it I didn't understand the issue you have created what you gonna do in this

**Comment by smog-root** [comment]
I can also add a timers functionality for it!!

To reduse Mass Upload!

**Comment by smog-root** [comment]
I will add a timmer for user. After one upload. The user needs to wait 60 sec (1min). To upload another file. This was anyone can't MASS upload!

**Comment by Harshdev098** [comment]
> Are you talking about increasing the size limit or what can you explain it I didn't understand the issue you have created what you gonna do in this

?

**Comment by smog-root** [comment]
> I will add a timmer for user. After one upload. The user needs to wait 60 sec (1min). To upload another file. This was anyone can't MASS upload! Using a automated script!!

.....

**Comment by smog-root** [comment]
**Adding a timer for file uploads every 60 seconds can provide several benefits:**

**Controlled Uploads:** 

Helps manage server load by preventing too many simultaneous uploads, which can lead to congestion.

**Data Integrity:**

Spacing uploads can reduce the risk of file corruption, especially if multiple large files are being uploaded.

**Comment by Harshdev098** [comment]
It will not be the case in future.
Adding this feature is not generic to the project for longer term. Uploading the research paper and university binding and enhancing the research ecosystem will be a lot more than this

I am closing this issue for now ,
You can refer the created issue or create one another
