### ISSUE TITLE
Feature : Adding website visits count in footer

### ISSUE THREAD

**Issue by ygowthamr** [Harshdev098/Research-Nexas#158]
#### Description
1. Display a dynamic counter in the footer to show the total number of website visits.  
2. The counter will update in real-time with each new visitor session.  
3. Use server-side logic to store and track visit counts in a database or a file.  
4. The count can reset periodically or accumulate based on configuration preferences.  
5. This feature enhances user engagement and provides site owners with basic analytics.

### Image for reference: 
 - 
![image](https://github.com/user-attachments/assets/639caea4-e0fe-44b2-9861-c65b06bc4014)

@Harshdev098 Assign me this issue give me labels like level3,gssoc-extd,hacktoberfest,etc.

**Comment by Harshdev098** [comment]
I can't prefer to add this in the website
