### ISSUE TITLE
Adding input validation

### ISSUE THREAD

**Issue by Gauravtb2253** [Harshdev098/Research-Nexas#17]
Hello I would like to add client side input validation to the login and register pages
Pls assign me this issue under hacktoberfest and gssoc extd

Thank you

**Comment by ADeshmukh80** [comment]
I kindly request to be assigned this task.

**Comment by Harshdev098** [comment]
The same issue has been opened in #16 ,for now i am closing it
@ADeshmukh80  You can work on this issue #16
