### ISSUE TITLE
[BUG]: Insertion of faculty information in "faculty" table while allotment of paper by stakeholder

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#175]
**Describe the bug**
When the stakeholder is allotting a paper to a faculty, an error is generated while insertion of faculty information in the `faculty` table.
`Error: ER_BAD_NULL_ERROR: Column 'email' cannot be null`

**To Reproduce**
1. Login as a **stakeholder**
2. Go to **Allot** paper page
3. Click on **View** of a paper that has been approved before.
4. Enter the email of faculty and click on **Allot**

**Expected behavior**
Insertion of faculty information in the faculty table.

**Screenshots**
None

**Additional context**
Wrong SQL query used.

@Harshdev098 Please assign this issue to me and add `hacktoberfest` and `gssoc-ext` labels to it.

**Comment by trinetra110** [comment]
@Harshdev098 Please also assign a level label to it.

**Comment by Harshdev098** [comment]
Will add once you open a pr regarding the issue

**Comment by trinetra110** [comment]
Ok
