### ISSUE TITLE
[FEATURE]: Choose-template for Signup option

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#176]
**Is your feature request related to a problem? Please describe.**
The Login button gives 3 options: `Student`, `Stakeholder` and `Faculty`. But there's no such template for signup option

**Describe the solution you'd like**
Make a choose-template for signup, adding 2 options: `Student` and `Stakeholder` that will redirect to their respective pages.

**Additional context**
@Harshdev098 Please assign this issue to me and add `hacktoberfest` and `gssoc-ext` labels to it.

**Screenshot**
![Screenshot 2024-10-17 000850](https://github.com/user-attachments/assets/3eca8956-bab4-447d-a44b-d0c0ec4defdc)

**Comment by trinetra110** [comment]
@Harshdev098 Please look into this.

**Comment by Harshdev098** [comment]
there is a register btn in landing page which links to the signup page of the researchers you can make similar choose_file page which redirects to the signup page of appropriate user
