### ISSUE TITLE
fix:Replication of uploaded files

### ISSUE THREAD

**Issue by Harshdev098** [Harshdev098/Research-Nexas#19]
**Describe the bug**
Clicking multiple times on view button, will replicate the same files giving same files number of times

**To Reproduce**
1. Go to upload research paper page
2. Click on upload a file
3. Click on view button multiple times, it will replicate the same file

**Screenshots**
![Screenshot from 2024-10-02 21-52-53](https://github.com/user-attachments/assets/763d1bd2-c1a7-411d-a4d3-512532b0aa1d)

**Comment by Gauravtb2253** [comment]
I can work on this issue
Can you pls describe in more detail exactly what you need

**Comment by taansssss** [comment]
@Harshdev098  Please assign me this issue. I would like to work on this.
Please assign me under GSSOC'24 extended.

**Comment by Harshdev098** [comment]
@Gauravtb2253  Hey, did you want to work on this issue

**Comment by Gauravtb2253** [comment]
> @Gauravtb2253 Hey, did you want to work on this issue

yes sure

**Comment by MitulSonagara** [comment]
@Harshdev098 

If this issue is solved then please close this so that contributors not get confused
