### ISSUE TITLE
Make the footer section more interactive with CSS Styling and Animations

### ISSUE THREAD

**Issue by ThunderShadows** [Harshdev098/Research-Nexas#193]
The footer section looks static and less responsive and providing a less dynamic user experience. 

@Harshdev098 

I would like to make the footer section more interactive and dynamic by adding more CSS Styling and Animations. Making sure to make it more responsive and user friendly for the website. Something similar like this--

![Screenshot 2024-10-07 225715](https://github.com/user-attachments/assets/d540d36b-d248-4534-95e4-a15297a4dd4a)

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by sayiamarora** [comment]
Hey @Harshdev098 could you assign me this issue. if it is not attempted and still open.
