### ISSUE TITLE
[FEATURE]: Add FAQ section

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#194]
**Is your feature request related to a problem? Please describe.**
A FAQ section should be present on a website for clarifying common doubts of the users.

**Describe the solution you'd like**
Adding a FAQ section would solve this problem. It should also be responsive across various devices.

**Additional context**
None

@Harshdev098 Please assign this issue to me and add 'hacktoberfest', 'gssoc-ext' and 'level2' labels to it.

**Comment by karandevhub** [comment]
\assign

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by Harshdev098** [comment]
Someone is already assigned this
If he can't will assign it to you

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.
