### ISSUE TITLE
[BUG]: Size of the dark-theme icon is huge in Stakeholder's main page

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#195]
**Describe the bug**
Size of the dark-theme icon is huge in Stakeholder's main page

**To Reproduce**
1. Go to Login page of Stakeholder
2. Login with your details and you will be redirected to the main page of Stakeholder

**Expected behavior**
Appropriate size of the dark-theme icon in the top right corner of the page like other pages

**Screenshots**

- Desktop/laptop
![Screenshot 2024-10-18 125659](https://github.com/user-attachments/assets/4cf62e89-30e6-4a7a-8681-82ef4fbcebd5)

- Phone
![Screenshot 2024-10-18 125903](https://github.com/user-attachments/assets/e2ad7b89-a696-4483-9921-5ec0fbf44c3b)

**Additional context**
None

@Harshdev098 Please assign this issue to me and add 'hacktoberfest', 'gssoc-ext' and a 'level' labels to it.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.

**Comment by karandevhub** [comment]
I'd like to work on this issue for Hacktoberfest! Please assign it to me.
