### ISSUE TITLE
Complete Image is not visible on home page.

### ISSUE THREAD

**Issue by Sudhanshu248** [Harshdev098/Research-Nexas#198]
The images are not visible properly due to  website view does not look good.
Along with some not required text were also present on images.

I would like to solve this issue.

![Screenshot 2024-10-18 143353](https://github.com/user-attachments/assets/190f70bc-a1c2-4998-b036-2e7efed10719)

Some not required text were present on images:
![Screenshot 2024-10-18 144606](https://github.com/user-attachments/assets/f947c216-00c6-421d-81b6-ee37c0db7936)

@Harshdev098  Kindly assign me the issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by Sudhanshu248** [comment]
@Harshdev098 Kindly assign me the issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by Harshdev098** [comment]
Someone is already working on it
