### ISSUE TITLE
Improve the UI of website

### ISSUE THREAD

**Issue by Gauravtb2253** [Harshdev098/Research-Nexas#2]
Hello sir,
I would like to improve the UI of the home page and login pages
Please assign this issue to me under Hacktoberfest label
Thank you

**Comment by Harshdev098** [comment]
Sure @Gauravtb2253 , Please go ahead!

**Comment by Gauravtb2253** [comment]
sir please add Hacktoberfest label

**Comment by janhavi7276** [comment]
sir would like to work on this issue as a quality UI can make a website feel trustworthy and build confidence in users.
please assign me

**Comment by Harshdev098** [comment]
@janhavi7276 This issue has been solved by #6  You can open another issue regarding home page UI enhancement. For now I am closing this issue

**Comment by janhavi7276** [comment]
yes sure
