### ISSUE TITLE
Fix the Language change option at its right place.

### ISSUE THREAD

**Issue by Sudhanshu248** [Harshdev098/Research-Nexas#201]
Currently the language change option is in the navbar which is not correct.

It should be show at the bottom of the screen. As the other pages. In the other pages- contact us, register, and login.  that option is placed at the right-bottom of the screen.

![Screenshot 2024-10-18 162104](https://github.com/user-attachments/assets/6e27caba-626e-481b-a53a-b88bc079ee9d)

I would like to solve this issue.

**Comment by Sudhanshu248** [comment]
@Harshdev098 Kindly assign me the issue under the label of gssoc-ext, hacktoberfest'24, hacktoberfest-accepted, level-2.

**Comment by Pratikpawar13** [comment]
@Harshdev098 Dear sir please assign me this issue ,I'll solve it as early as possible.

**Comment by Harshdev098** [comment]
its already fixed
