### ISSUE TITLE
Updating the signup backend

### ISSUE THREAD

**Issue by Harshdev098** [Harshdev098/Research-Nexas#22]
## Current behaviour
Our Signup logic is to check the existing user with the entered email and if found it will give `user already exist` if not, it will insert the user data  

## Expected behaviour 
The logic should be, it check the existing user with entered email and username and if found it will give `user already exist` if not, it will insert the user data. The change is that, it should check for the username rather than checking only for entered email.

**Comment by RishiVT2004** [comment]
you can assign me this @Harshdev098 , i have previous experience in working in login and signup routes

**Comment by RishiVT2004** [comment]
Thank you for assigning me , I will work on it asap
