### ISSUE TITLE
FIXING THE Prerequisites Section

### ISSUE THREAD

**Issue by alo7lika** [Harshdev098/Research-Nexas#225]
**Describe the bug**  
The Prerequisites section in the README file is unclear and lacks specific details regarding software requirements, which can lead to confusion for users trying to set up the application.

**To Reproduce**  
1. Go to the README file of the project repository.
2. Locate the Prerequisites section.
3. Review the listed software requirements.
4. Observe that there are no versions specified or links to download the software.

**Expected behavior**  
The Prerequisites section should clearly list the required software along with their respective versions and direct links to download or install them. This will provide users with a better understanding of what is needed to run the application.

**Screenshots**  

**Additional context**  
Providing detailed prerequisites is essential for ensuring that users can set up the environment correctly. Lack of clarity may lead to issues during installation, resulting in frustration and potential abandonment of the project.

**Comment by alo7lika** [comment]
ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 
ASSIGN ME THE TASK @Harshdev098 
Thank you!

**Comment by Harshdev098** [comment]
Its not needed, I will dockerize the repository soon
