### ISSUE TITLE
Updation of contributing.md file

### ISSUE THREAD

**Issue by Nikhil0-3** [Harshdev098/Research-Nexas#226]
Wanted to do the following changes :-

Enhance the project structure
Add the help and support section
Add the pull request section
Add issue report process section

**Comment by Harshdev098** [comment]
someone is already working on it. Will assign if he can't

**Comment by Nikhil0-3** [comment]
I have updated the conducting.md file . If any further changes required tell me.

**Comment by Nikhil0-3** [comment]
Please assign me this work.

**Comment by Nikhil0-3** [comment]
I have updated contributing.md file please check it. If any further changes required please tell me.
