### ISSUE TITLE
[FEATURE]: Adding the Chatbot in Stakeholder's main page

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#232]
**Is your feature request related to a problem? Please describe.**
There is no Chatbot present in Stakeholder's main page.

**Describe the solution you'd like**
Adding a Chatbot helps users to resolve common queries quickly.

**Screenshot**

![Screenshot 2024-10-20 122730](https://github.com/user-attachments/assets/9e9d8406-2590-4fbb-9990-761bfe36e714)

**Additional context**
None

@Harshdev098 Please assign this issue to me and add 'hacktoberfest', 'gssoc-ext' and 'level' labels to it.

**Comment by Harshdev098** [comment]
Someone is already working on it
