### ISSUE TITLE
Log out is not working 

### ISSUE THREAD

**Issue by MrunalKashid02** [Harshdev098/Research-Nexas#237]
**Describe the bug**
I login as stakeholder and found that logout is not working

**Expected behavior**
After clicking logout it should be redirected to login page or home page

**Screenshots**

https://github.com/user-attachments/assets/6520497b-b360-41e5-a62f-11b10ab13a92

**Additional context**

if this issue is previously not addressed i want to work on this

**Comment by MrunalKashid02** [comment]
whenever i tried to register for faculty i am getting this error 

![reasearch issue](https://github.com/user-attachments/assets/98759484-56ed-4389-8795-a49ea4078d63)

**Comment by MrunalKashid02** [comment]
I have created draft pr and add logout  functionality for student and stakeholder but for faculty i am not able to login. please take a look.

**Comment by MrunalKashid02** [comment]
This functionality not implemented yet right ?

**Comment by Harshdev098** [comment]
It's already implemented

**Comment by MrunalKashid02** [comment]
is someone also working on logout function because i find logout file
![Screenshot 2024-10-21 155910](https://github.com/user-attachments/assets/b83efc7f-0543-400d-8f10-b7551a0c1a13)

**Comment by Harshdev098** [comment]
I think someone has already worked on it but its not working

**Comment by MrunalKashid02** [comment]
i have wriiten code a diffrent way as you can see in PR. can i remove this code or modify.

**Comment by MrunalKashid02** [comment]
I dont know but accidentally closed the pull request can i raised it again ?
