### ISSUE TITLE
[BUG]: The "Follow us" section is not properly placed in the Student's main page

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#241]
**Is your feature request related to a problem? Please describe.**
Follow us section not properly placed.

**Describe the solution you'd like**
Adding responsive "Follow us" section in student's main page like in home page would increase the interaction and global presence.

**Screenshots**

![Screenshot 2024-10-20 144948](https://github.com/user-attachments/assets/346d464a-f50c-4c86-83d2-72056348695b)

![Screenshot 2024-10-20 145003](https://github.com/user-attachments/assets/f742ba06-4e57-4b6b-b5eb-67dfa093e70c)

**Additional context**
None

@Harshdev098 Please assign this issue to me and add 'hacktoberfest', 'gssoc-ext' and 'level3' labels to it.

**Comment by Pratikpawar13** [comment]
@Harshdev098 Please assign this issue to me , I'll solve this issue as early as possible.
