### ISSUE TITLE
Automated project structure updation using github workflows and action bot

### ISSUE THREAD

**Issue by J-B-Mugundh** [Harshdev098/Research-Nexas#247]
**Is your feature request related to a problem? Please describe.**
Currently, people doesn't know the exact project structure clearly before hand in readme. 

**Describe the solution you'd like**
I want to automate project structure updation using github workflows and action bot

**Comment by J-B-Mugundh** [comment]
@Harshdev098 Please assign me this issue. It'll be useful for this project

**Comment by Harshdev098** [comment]
Can you describe what you gonna do in it @J-B-Mugundh

**Comment by J-B-Mugundh** [comment]
Currently, our repository doesn't have project structure. And, it would be a bit difficult for new commers to understand the project structure completely. Also, it's difficult for us to manually change the project structure as well update things everyday. So, we could automate this with github workflows, python script and actions bot. 

Sample of how the workflow has been automated and the project structure is updated in readme

![image](https://github.com/user-attachments/assets/eab22e38-2835-4211-9ffb-866be7a131d3)
