### ISSUE TITLE
Migrating DB to PostgreSQL for better integration with Supabase

### ISSUE THREAD

**Issue by shrek-28** [Harshdev098/Research-Nexas#26]
Is your feature request related to a problem? Please describe.
I'm contributing to this open-source project by helping migrate the current database to PostgreSQL to host it on Supabase. The current database may limit the project's potential scalability and cloud-native functionality. Migrating to PostgreSQL on Supabase will allow for better performance, scalability, and integration with cloud services.

Describe the solution you'd like
I propose migrating the existing database to PostgreSQL and setting it up on Supabase. The solution includes migrating all current data, adjusting the database configurations, and ensuring compatibility of all database queries with PostgreSQL. The deployment link for Supabase hosting would also be included for easier collaboration and use.

Additional context
Supabase provides a managed PostgreSQL solution with features like real-time data, API generation, and integrated authentication, which could benefit the project in the long run. This migration would enhance the open-source project's capability to handle a larger user base and facilitate contributions from the community.

**Comment by Harshdev098** [comment]
In future, there is a chance that it can be changed but for now we will go with MySQL only. Although if you want to contribute, you can go with other issues or new issue it will be appreciable
