### ISSUE TITLE
[FEATURE REQUEST]: Implement Real-Time Search Functionality for FAQs

### ISSUE THREAD

**Issue by PrityanshuSingh** [Harshdev098/Research-Nexas#261]
### Is your feature request related to a problem? Please describe.  
Currently, there is no search functionality in the FAQ section, making it difficult for users to find specific information quickly. This can lead to frustration and a poor user experience when trying to locate relevant FAQs.

### Describe the solution you'd like.  
Implement a real-time search feature that allows users to enter keywords in a search bar. The FAQ section should dynamically display the matching FAQs as the user types, providing a more efficient way for users to find answers. This feature should also highlight relevant keywords within the FAQs.

### Add any other context or screenshots about the feature request here.  
Implementing this feature will significantly enhance user experience by making it easier for users to find specific information quickly without scrolling through multiple FAQs.

![image](https://github.com/user-attachments/assets/7869322a-356f-44c1-9643-32d10f1a112d)

@Harshdev098  Please assign this issue to me under gssoc-ext level3 and hactoberfest-accepted, as I am interested in working on it.

**Comment by PragnyaRavikumar** [comment]
I would like to work on this issue, please assign it to me.

**Comment by PrityanshuSingh** [comment]
@Harshdev098 I was travelling for a day, will try to generate the PR today.
