### ISSUE TITLE
[FEATURE REQUEST]: Implement Sliding Navbar for Mobile View

### ISSUE THREAD

**Issue by PrityanshuSingh** [Harshdev098/Research-Nexas#262]
### Is your feature request related to a problem? Please describe.  
Currently, the mobile view of the website lacks a sliding navbar feature. Users cannot easily navigate the site due to the absence of a responsive navigation solution, which can lead to a cumbersome experience when accessing different sections.

### Describe the solution you'd like.  
Implement a sliding navbar that appears from the left side of the screen when the user clicks on the hamburger icon in mobile view. This functionality should provide an intuitive and seamless navigation experience for users on mobile devices.

### Add any other context or screenshots about the feature request here.  
Implementing this feature will significantly improve the usability of the site on mobile devices, allowing users to navigate more easily and efficiently.

![image](https://github.com/user-attachments/assets/8bcf75fc-b2cb-42fa-8e82-e7879ad18e50)

@Harshdev098  Please assign this issue to me under gssoc-ext level3 and hactoberfest-accepted, as I am interested in working on it.

**Comment by ShudarsanRegmi** [comment]
@PrityanshuSingh What is the tool you are using to check the responsiveness?

**Comment by PrityanshuSingh** [comment]
> @PrityanshuSingh What is the tool you are using to check the responsiveness?

It's a chrome extension, viewport resizer. It's quite handy.

**Comment by PrityanshuSingh** [comment]
@Harshdev098 are there any conflicts or necessary changes you want me to include in the PR in order to get it merged.

**Comment by Harshdev098** [comment]
Will let you know more till night

**Comment by PrityanshuSingh** [comment]
> Will let you know more till night

@Harshdev098 Should I generate a new PR regarding this issue before moving to other issues?

**Comment by PrityanshuSingh** [comment]
@Harshdev098 if there are any conflicts with the existing codebase, kindly inform, i will generate a new PR accordingly.
