### ISSUE TITLE
Github actions for more connectivity!

### ISSUE THREAD

**Issue by smog-root** [Harshdev098/Research-Nexas#263]
**We can implement github workflows for the following things:**

1. Auto comment on issue **Closed** and **Opened**
2. Auto comment on **PR mergs**
3. Auto comment on **PR raises**

Using this workflows makes you'r repo more interactive ! @Harshdev098 

_**i'm expecting a level3 with gssoc-ext and hacktoberfest-accepted label**_

**Comment by Harshdev098** [comment]
Its already done for PR raises and issue raises if you want just add it for pr merges

**Comment by smog-root** [comment]
Yaa.  I can do that!!
