### ISSUE TITLE
improving ui of about us section

### ISSUE THREAD

**Issue by agarwalbhargavi** [Harshdev098/Research-Nexas#297]
<img width="958" alt="Screenshot 2024-10-23 222324" src="https://github.com/user-attachments/assets/0bd371e7-d091-41b1-8e80-2ee7a58c4f47">
here the images and text are overlapping which is not looking good..i would like to work on this.
@Harshdev098

**Comment by agarwalbhargavi** [comment]
@Harshdev098 kindly assign me this

**Comment by agarwalbhargavi** [comment]
<img width="959" alt="Screenshot 2024-10-23 225924" src="https://github.com/user-attachments/assets/503f5a79-d9de-4f1b-855e-17314ff14d8d">
here is the resolved solution 
@Harshdev098

**Comment by agarwalbhargavi** [comment]
@Harshdev098 kindly reply

**Comment by Harshdev098** [comment]
@agarwalbhargavi Someone is already working on it

**Comment by agarwalbhargavi** [comment]
@Harshdev098  this issue is still not resolves can u reassign me this?
