### ISSUE TITLE
Add eye button in password section ✨

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Harshdev098/Research-Nexas#300]
I want to create a show hide password, eye button in both Login & Registration page..

PA please assign me this task.

![Screenshot 2024-10-23 225341](https://github.com/user-attachments/assets/b475d1c6-b84f-477d-a6b8-958ab37d66df)
![Screenshot 2024-10-23 225348](https://github.com/user-attachments/assets/2dcb128d-5052-4059-aafb-364b54221988)

**Comment by Subhajit-2023-44** [comment]
@Harshdev098 assign me this task with Level 3 because I want to create a show hide password, eye button in both Login & Registration page..

**Comment by Harshdev098** [comment]
Someone is already working on it
