### ISSUE TITLE
📝[DOCS] adding Stargazers and Forkers section to readme.md

### ISSUE THREAD

**Issue by amiya-cyber** [Harshdev098/Research-Nexas#301]
Issue Description

adding Stargazers and Forkers section to readme.md

Suggested Change

we can add Stargazers and Forkers section to readme.md

Stargazers

Use Case:

1. Bookmarking Projects
2. Discovering Popularity

Benefits:

1. Visibility
2. Feedback Indicator
3. Community Engagement

Forkers

Use Case:

1. Creating Personal Copies
2. Contributing Back

Benefits:

1. Encouraging Innovation
2. Easy Collaboration
3. Building Ownership

![2024-10-23 (7)](https://github.com/user-attachments/assets/cbe8a473-d8af-4019-994e-fbaa217ea8ca)

ADD LABELS HACKTOBERFEST AND GSSOC EXT 24 AND LEVEL 2 OR LEVEL 3
ASSIGN ME THE WORK
THANK YOU @Harshdev098  !

**Comment by Harshdev098** [comment]
Not necessary
