### ISSUE TITLE
Improving Password Validation during login and signup of Users

### ISSUE THREAD

**Issue by RishiVT2004** [Harshdev098/Research-Nexas#31]
While going through the login and signup routes I noticed that the password validation can be done better  

An optimal password validation system needs to be done to ensure better input validation while signup and login

**Comment by RishiVT2004** [comment]
@Harshdev098 please assign this to me and add hacktoberfest and gssoc-ext labels in it

**Comment by RishiVT2004** [comment]
@Harshdev098 is it okay to implement rate limiters using express js

**Comment by Harshdev098** [comment]
@RishiVT2004 yah, Sure
