### ISSUE TITLE
Add a "Add topic" page for Student

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#334]
**Is your feature request related to a problem? Please describe.**
The "add topic" button doesn't work in the student's main page.

**Describe the solution you'd like**
Adding a "add topic" page for student (frontend only).

**Screenshot**

![Screenshot 2024-10-30 122407](https://github.com/user-attachments/assets/74bcbc6c-fc7b-4301-a7ff-33985b6bf6ea)

**Additional context**
None

@Harshdev098 Please assign this issue to me and add 'hacktoberfest', 'gssoc-ext' and a 'level' labels to it.

**Comment by Harshdev098** [comment]
Will add levels after opening of the PR
