### ISSUE TITLE
Add a "Approve Topics" page for Stakeholder

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#335]
**Is your feature request related to a problem? Please describe.**
The "approve topics" button doesn't work in the stakeholder's main page.

**Describe the solution you'd like**
Adding a "approve topics" page for stakeholder (frontend only).

**Screenshot**

![Screenshot 2024-10-30 122544](https://github.com/user-attachments/assets/1f9607a0-1284-440b-bd2f-ec784d246a65)

**Additional context**
None

@Harshdev098 Please assign this issue to me and add 'hacktoberfest', 'gssoc-ext' and a 'level' labels to it.

**Comment by Harshdev098** [comment]
Will add levels after opening of the PR
