### ISSUE TITLE
UI/UX Enhancements: Logo Consistency, Button Navigation, and Page Redirection Fixes

### ISSUE THREAD

**Issue by ragini-gp** [Harshdev098/Research-Nexas#34]
The current logo does not look good in violet background
![image](https://github.com/user-attachments/assets/e68ddf4f-ef50-4c4f-a1fe-df4514c19b4c)

This would look better
![image](https://github.com/user-attachments/assets/ba7cf7bd-eb55-49d3-9384-64c32bce7b7c)

Will change this for all sign up/register page, login page

Clicking on About us not taking to About Us section
![image](https://github.com/user-attachments/assets/000a4fce-9d25-47d5-abd8-c782bb6c7727)

![image](https://github.com/user-attachments/assets/2a30444c-3f2f-41c8-849d-5e54607ff872)

Register button not taking to regoster page
![image](https://github.com/user-attachments/assets/1433ba1f-fe4e-4dd5-80bc-facd45552199)

I can resolve these issues, please assign under hacktoberfest-accepted, gssoc-ext, with level

**Comment by Harshdev098** [comment]
It will also work, the `hacktoberfest-accepted` label is added in the PR but its also not such important the `hacktoberfest`label on issues and repo will work enough

**Comment by ragini-gp** [comment]
Ok, sure. Thanks

**Comment by Harshdev098** [comment]
I think the links you are refering is already fixed by someone in their PRs. There are many things which can be fixed in index page if you wonna want to solve, please go ahead in this issue

**Comment by ragini-gp** [comment]
Ok

**Comment by ragini-gp** [comment]
Also, should I proceed with the "Research Nexas" image I suggested above ?

**Comment by ragini-gp** [comment]
Okay, I will fix other issues

**Comment by Harshdev098** [comment]
Sure
