### ISSUE TITLE
Add dark mode

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Harshdev098/Research-Nexas#347]
I want to add dark mode properly.
PA please assign me this task.

**Comment by Subhajit-2023-44** [comment]
@Harshdev098

**Comment by Harshdev098** [comment]
Not necessary to add it on home page

**Comment by Subhajit-2023-44** [comment]
> Not necessary to add it on home page

@Harshdev098 sir please let me know if there is any other task..

**Comment by Harshdev098** [comment]
Yah sure

**Comment by Subhajit-2023-44** [comment]
> Yah sure

Yes sir please let me know I will try to solve your task, I am a gssoc-ext contributor and I really need points..

Thank You
