### ISSUE TITLE
Enhancing the "premium" section css styling and improving alignment, adding relevant information removing irrelevant info.

### ISSUE THREAD

**Issue by shriyadindi** [Harshdev098/Research-Nexas#358]
Enhancing the "premium" section css styling and improving alignment, adding relevant information removing irrelevant info.
![Screenshot 2024-10-31 204251](https://github.com/user-attachments/assets/a2ff4342-b7e3-427d-abde-133f51888f69)

**Comment by Harshdev098** [comment]
WIll add level label after opening of PR
