### ISSUE TITLE
Feature : Adjusting the Alignment of Homepage Components

### ISSUE THREAD

**Issue by ygowthamr** [Harshdev098/Research-Nexas#368]
### Issue: Adjusting the Alignment of Homepage Components

1. **Assessing Alignment**: Reviewing the layout of homepage components.
2. **Making Adjustments**: Realigning elements for consistent spacing and balance.
3. **Testing Responsiveness**: Ensuring the layout looks good on various devices.
4. **Maintaining Design Consistency**: Aligning changes with design standards.
5. **Documenting Changes**: Capturing before-and-after screenshots for reference.

@Harshdev098 
Pls assign me this issue, give me labels, level, etc.

**Comment by ygowthamr** [comment]
@Harshdev098 
Pls give me level3 to this issue.

**Comment by Harshdev098** [comment]
Will give levels after opening of the PR, don't worry
