### ISSUE TITLE
Feature: Improve design of dashboard page for student

### ISSUE THREAD

**Issue by mehul-m-prajapati** [Harshdev098/Research-Nexas#376]
**Is your feature request related to a problem? Please describe.**
- Current design seems to be very basic and not appealing to users.

**Describe the solution you'd like**
- Use bootstrap or other CSS libs to improve UI/UX

**Additional context**
![c1](https://github.com/user-attachments/assets/eabcfa5d-b4f0-43c1-bdb0-3cd970f410aa)

**Comment by Harshdev098** [comment]
Will give levels after opening of the PR
