### ISSUE TITLE
Feature : Prevent Application Crash on Database Connection Failure

### ISSUE THREAD

**Issue by ygowthamr** [Harshdev098/Research-Nexas#384]
# Prevent Application Crash on Database Connection Failure

**Description**:  
Implement error handling to prevent application crashes when database connections fail. Display an alert to inform users of the connection issue, and, if possible, provide a "Retry" option or guidance on next steps.

**Images for reference:**
 - ![image](https://github.com/user-attachments/assets/fdd7fe82-cd8c-4668-9194-46f0f22f0603)

@Harshdev098
Pls assign me this issue, give me labels and level.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshdev098** [comment]
Will add level label after opening of the PR

**Comment by ygowthamr** [comment]
@Harshdev098 
Okay

**Comment by VijayBhandari2002** [comment]
I could make it more secure can you please assign it to me. So i can make valuable contribution to it.
