### ISSUE TITLE
Feat: Adding "remember me" to the signup and signin page connecting it to the local storage database for user authentication.

### ISSUE THREAD

**Issue by shriyadindi** [Harshdev098/Research-Nexas#390]
### Describe the feature

Adding "remember me" to the signup and signin page connecting it to the local storage database for user authentication.

### Add ScreenShots

![image](https://github.com/user-attachments/assets/44ec361d-53a2-413c-9c7e-8d589cc22cfb)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Harshdev098** [comment]
Will enhance this feature to by default,
Not needed for now
