### ISSUE TITLE
Front End Issue Report Template

### ISSUE THREAD

**Issue by alo7lika** [Harshdev098/Research-Nexas#393]
A Frontend Issue Report Template is necessary to ensure that bugs and feature requests related to the user interface are communicated clearly and consistently, improving the speed and accuracy of issue resolution. It helps capture essential details, such as device and browser information, screen resolutions, and specific steps to reproduce the issue, which are critical in frontend development where visual appearance and functionality can vary across environments. By standardizing these reports, the template reduces ambiguity and eliminates the need for back-and-forth clarification, saving time for both the reporter and frontend developers. It prompts reporters to include screenshots, error logs, or screen recordings, offering developers a visual reference that speeds up debugging and improves communication. Additionally, a well-organized frontend issue report template helps the team prioritize work, maintain a record of issues for future reference, and identify trends in common UI/UX problems, ultimately leading to a smoother, more efficient development process.

![Screenshot 2024-11-05 000226](https://github.com/user-attachments/assets/5c1024a8-f120-458a-a4ea-b6a1858b9b22)

**Comment by alo7lika** [comment]
@Harshdev098 assign me the task under GSSOC (Level 2)

**Comment by alo7lika** [comment]
> @Harshdev098 assign me the task under GSSOC (Level 2)

@Harshdev098

**Comment by Harshdev098** [comment]
Not mandatory
