### ISSUE TITLE
[Bug]: Newsletter Popup Reappears on Every Page Load

### ISSUE THREAD

**Issue by ygowthamr** [Harshdev098/Research-Nexas#394]
### Description

The newsletter popup is currently appearing every time the page loads, causing inconvenience for users. Once a user clicks the "No Thanks" button on the newsletter popup, it should not appear again during future visits for the same user.

### Screenshots

 - ![image](https://github.com/user-attachments/assets/583c53f6-4c70-4f2e-a578-365ec1390bf2)

### Any additional information?

@Harshdev098 Pls assign me this issue, give me labels, level.

### What browser are you seeing the problem on?

Firefox, Chrome, Safari, Microsoft Edge

### Checklist

- [X] I have checked the existing issues
- [X] I have read the [Contributing Guidelines](https://github.com/alo7lika/Research-Nexas/blob/DEV/Contributing.md)
- [X] I'm a GSSoC'24-Extd contributor
- [X] I'm a Hacktoberfest'24 contributor
- [X] I am willing to work on this issue (optional)

**Comment by Harshdev098** [comment]
I didn't think it should be the case, its not pop up in my firefox

https://github.com/user-attachments/assets/4f14ba7a-5249-4962-8723-48b5f9683e7d

**Comment by ygowthamr** [comment]
@Harshdev098 
Check in Google.
