### ISSUE TITLE
Link is not working in the allotment.html (for stakeholders)

### ISSUE THREAD

**Issue by Harshdev098** [Harshdev098/Research-Nexas#4]
## Current Behaviour
`View the File` link is not working for the stakeholder while allotment and approval of paper

![Screenshot from 2024-10-01 02-02-22](https://github.com/user-attachments/assets/6ed42f7d-9ac3-4429-9037-3b365289ef08)

**Comment by ctosedots** [comment]
Sir i will do this task pls assign me

**Comment by ygowthamr** [comment]
Sir pls assign me this task i will do it

**Comment by Harshdev098** [comment]
Sure, Please go ahead will review your PR, Assigned!

**Comment by ygowthamr** [comment]
Sir can you pls add tags to my assignment

**Comment by ygowthamr** [comment]
Sir you have not added the wrong label it is not gssoc-ext it is gssoc-extd and also given me the level 3 label

**Comment by ygowthamr** [comment]
@Harshdev098 
please don't take any decisions i am working on it. I am bit busy in some works and now i am focusing on this issue.

**Comment by MitulSonagara** [comment]
@Harshdev098 

If @ygowthamr is working on it then it is totally fine.
