### ISSUE TITLE
Feat: Add cursor effect on all the pages

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#401]
### Describe the feature

Adding cursor effect on all the pages attracts users.

### Add ScreenShots

![Screenshot (42)](https://github.com/user-attachments/assets/c547aa20-2767-498c-b3b8-4c2f1fbea2c3)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trinetra110** [comment]
@Harshdev098 Please assign this issue to me and add 'gssoc-ext' and a 'level' labels to it.

**Comment by Harshdev098** [comment]
not good idea keep it only on home page

**Comment by Harshdev098** [comment]
@trinetra110  Instead if you want can make the home page responsive you can raise an issue regarding that
