### ISSUE TITLE
Feat: Add a new responsive contributors page 🔴

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Harshdev098/Research-Nexas#409]
### Describe the feature

I want to add a new responsive contributors page..

https://github.com/user-attachments/assets/a35fbbd1-d1b7-4574-81d0-9bd40a212dc3

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit-2023-44** [comment]
@Harshdev098 sir please assign me

**Comment by Subhajit-2023-44** [comment]
@Harshdev098

**Comment by Harshdev098** [comment]
It's already there

**Comment by Subhajit-2023-44** [comment]
> new responsive contributors page..

@Harshdev098 sir but not responsive contributors page..
