### ISSUE TITLE
Feat: Writing SQL code and API endpoints for adding and approving the topics

### ISSUE THREAD

**Issue by trinetra110** [Harshdev098/Research-Nexas#417]
### Describe the feature

Currently, the Add topics and Approve topics pages don't have connections between each other, no real-time functioning. Adding SQL code and API endpoints for connecting these 2 will enhance the project. The student can add topics, and the stakeholder can see the pending topics and approve them.

### Add ScreenShots

![Screenshot 2024-11-09 014421](https://github.com/user-attachments/assets/9210889a-66de-4d6f-aac1-17a9c388a3ab)

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by trinetra110** [comment]
@Harshdev098 Please add the 'gssoc-ext' and 'level3' tags.

**Comment by trinetra110** [comment]
@Harshdev098 
I couldn't understand. Can you explain in detail ?
I have done the changes locally and it works fine.

**Comment by Harshdev098** [comment]
Actually there are many things related to this process is left 
Can't directly jump into this

**Comment by trinetra110** [comment]
> Actually there are many things related to this process is left Can't directly jump into this

@Harshdev098 Can you give example ? Then I'll raise issue for it and work on it.
