### ISSUE TITLE
Feat: Add Signup/Register page 🟢

### ISSUE THREAD

**Issue by Subhajit-2023-44** [Harshdev098/Research-Nexas#418]
### Describe the feature

I want to create a Signup/Register page.. please assign me..

### Add ScreenShots

.

### Record

- [X] I agree to follow this project's Code of Conduct
- [X] I'm a GSSOC'24 contributor
- [X] I want to work on this issue

**Comment by Subhajit-2023-44** [comment]
@Harshdev098 sir please assign me

**Comment by Harshdev098** [comment]
It's already there!!
