### ISSUE TITLE
Feat: Adding a password toggle btn for stakeholders

### ISSUE THREAD

**Issue by Harshdev098** [Harshdev098/Research-Nexas#420]
### Issue Summary

Enhancement

### Issue Description

Add a password toggle button in the password field of signup and login page for stakeholders

### Priority

Medium - Should be addressed soon

### Category

- [X] Enhancement
- [ ] Refactor
- [ ] Security
- [ ] Design
- [ ] Other

**Comment by trinetra110** [comment]
@Harshdev098 The password toggle button is also not present in the password field of the signup and login page for students, so I'll add it there too.

**Comment by Harshdev098** [comment]
A pull request is already open #95

**Comment by trinetra110** [comment]
> A pull request is already open #95 for that

Ok, then I'll only add for stakeholder.
