### ISSUE TITLE
Feat: Changing Website Logo 

### ISSUE THREAD

**Issue by Harshdev098** [Harshdev098/Research-Nexas#421]
### Describe the feature

Change the Research nexas logo on web pages where required with appropriate images

**Also remove the background from the image with help of background remover out there** 

### Add ScreenShots

![Screenshot from 2024-11-09 13-48-55](https://github.com/user-attachments/assets/09593ff1-3b65-46c2-b894-e24cd87e8e93)

![image](https://github.com/user-attachments/assets/7f219def-a7fe-4215-9d73-d6ac92bb993b)

![image](https://github.com/user-attachments/assets/94eb7fcd-0db4-4601-a0c8-9a435bc92398)

### Record

- [X] I agree to follow this project's Code of Conduct
- [ ] I'm a GSSOC'24 contributor
- [ ] I want to work on this issue

**Comment by trinetra110** [comment]
@Harshdev098 Please assign this issue to me.

**Comment by trinetra110** [comment]
> **Also remove the background from the image with help of background remover out there**
> 
> ### Add ScreenShots
> ![Screenshot from 2024-11-09 13-48-55](https://private-user-images.githubusercontent.com/118347330/384589014-09593ff1-3b65-46c2-b894-e24cd87e8e93.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzExNjc5MjksIm5iZiI6MTczMTE2NzYyOSwicGF0aCI6Ii8xMTgzNDczMzAvMzg0NTg5MDE0LTA5NTkzZmYxLTNiNjUtNDZjMi1iODk0LWUyNGNkODdlOGU5My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQxMTA5JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MTEwOVQxNTUzNDlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wMzNlNmIzYWJlY2VjNDBkZDkyMGNkZDZhNTY3MzQxZTdlOGU3ZGM3Y2UzYTZmYmFjYWMzMzg5YTZlNDkzYTJmJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCJ9.MfHvuQB7Ip4mlI_wZVlTnwaOGx6fsMSqkzrwQldC0uY)

@Harshdev098 By removing the background, do you mean like this ?

![logo1_test2](https://github.com/user-attachments/assets/fa96734b-fa10-4a8f-9f68-e0ea4254a036)

OR like this ?

![logo1_test](https://github.com/user-attachments/assets/8bf07191-ec02-4537-ba5a-b2595fd17d0e)

**Comment by Harshdev098** [comment]
I think the first one it should be transparent background it should not displayed(background colour)once on the website page

**Comment by trinetra110** [comment]
Ok got it.
