### ISSUE TITLE
Add a show/hide btn in password fields

### ISSUE THREAD

**Issue by Harshdev098** [Harshdev098/Research-Nexas#44]
There are all most 2 forms in the application. The problem in these forms is, there is no hide/show btn in the password field
A btn should be added in all the two form(login, signup) under password field to show and hide the password

**Comment by saumyap48** [comment]
hey i want this to fix it please assign me this .

**Comment by RNAdvani** [comment]
added this #95

**Comment by Harshdev098** [comment]
@saumyap48 already assigned this task if she will not fix it, will assign and merge your PR @RNAdvani

**Comment by saumyap48** [comment]
> added this #95
Aleady aasign to me
