### ISSUE TITLE
Adding dark mode toggle for entire website

### ISSUE THREAD

**Issue by Ankitha2130** [Harshdev098/Research-Nexas#49]
I will work on adding dark mode toggle for entire website.
Please assign this issue to me under gssoc-ext,hacktoberfest, and a suitable level

**Comment by Harshdev098** [comment]
Sure @Ankitha2130 , but don't add dark mode for home page(landing page of the website) its not very effective

**Comment by Ankitha2130** [comment]
Ok fine i will not add it to home page

**Comment by Ankitha2130** [comment]
Please add a suitable label also.
