### ISSUE TITLE
GSSOC EXT NOTICE: Improper Labeling in the Project

### ISSUE THREAD

**Issue by Meetjain1** [Harshdev098/Research-Nexas#56]
Dear Project Admin @Harshdev098 

It has come to our attention that your repository not applying the necessary labels to issues and merged PRs, which is affecting contributor scores on the leaderboard.

Please ensure you use the correct labels:

- gssoc-ext
- level1, level2, level3 
- hacktoberfest-accepted (only if your repository have Hacktoberfest topic in description)

*NOTE:* Level labels should not have any dashes between them. Spaces are allowed, but no dashes should be used.

Kindly review and update the labels on your issues and PRs to ensure fairness for all contributors. Failure to address this may result in your project being flagged.

Thank you,
Core Team
GSSoC '24 Extended

**Comment by Harshdev098** [comment]
@Meetjain1 Is it necessary to add labels in the PRs also

**Comment by Meetjain1** [comment]
> @Meetjain1 Is it necessary to add level labels in the PRs also

@Harshdev098 Yes in fact it is must to add labels In prs since Points are fetched through merged prs not through issues .

**Comment by Harshdev098** [comment]
@Meetjain1 Have added all the valid and necessary labels on issues and PRs

**Comment by Harshdev098** [comment]
@Meetjain1 I have reverted a PR should I give him the labels on that PR?
