### ISSUE TITLE
Refactor MySQL Connection Logic

### ISSUE THREAD

**Issue by harish08102004** [Harshdev098/Research-Nexas#59]
**Describe the bug**
Refactor the MySQL connection logic by creating a dedicated configuration module for handling the database connection pool instead of repeating the logic across multiple files.

**To Reproduce**

1. Check the existing codebase for multiple instances of MySQL connection pool creation.
2. Notice the redundancy in connection logic across different files.
3. Identify the need for a centralized configuration.

**Expected behavior**
A single dedicated module should handle the MySQL connection pool. This will improve maintainability and reduce redundancy in the codebase.

**Additional context**
Creating a config folder with a file named mysqlConnection.js will allow us to manage the MySQL connection more efficiently. This approach will facilitate changes and updates to the connection logic without affecting multiple files.

**Comment by harish08102004** [comment]
Hey @Harshdev098 please add label for this also.

**Comment by Harshdev098** [comment]
Its a big thing, I also wants to change the same. thanks for recognizing this issue
