### ISSUE TITLE
Add contributors to README automatically

### ISSUE THREAD

**Issue by jvkousthub** [Harshdev098/Research-Nexas#65]
**Is your feature request related to a problem? Please describe.**
There is no space for contributors of the project in README which can be added

**Describe the solution you'd like**
I will automate the task of adding contributors to README

**Additional context**

**Comment by jvkousthub** [comment]
@Harshdev098 I would like to work on this issue
I am a GSSoC'24 and Hactoberfest contributor

**Comment by Harshdev098** [comment]
Sure

**Comment by jvkousthub** [comment]
Please put level label
