### ISSUE TITLE
Add colorful,attractive follow us icons 

### ISSUE THREAD

**Issue by KapuluruBhuvaneswariVspdbct** [Harshdev098/Research-Nexas#70]
**Describe the bug**

**To Reproduce**
1. Go to 'research nexas website'
2. Click on 'website'
3. Scroll down to 'follow us at end
<img width="953" alt="researchnexas1" src="https://github.com/user-attachments/assets/e16365cb-b284-49f0-b1e7-d4e8fb3743af">
'

**Expected behavior**
 colorful,attractive follow us icons 

**Screenshots**

**Additional context**

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
kindly assign this task to me

**Comment by KapuluruBhuvaneswariVspdbct** [comment]
made this isssue corrected updated the colors on hovering 

https://github.com/user-attachments/assets/0f5de570-154d-4d0b-9d26-eb04af7ead84

**Comment by Shalinis19137** [comment]
I would like to work on your project can you please assign me this project to me under Gssoc - ext 2024
