### ISSUE TITLE
Quality of logo or design of logo is not good ,its unsymmetrical not proper designed

### ISSUE THREAD

**Issue by shruti9935** [Harshdev098/Research-Nexas#74]
**Describe the bug**

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**
Assign this task to me

**Comment by Harshdev098** [comment]
Sorry, but don't change the logo for now we will see it in future.
But yah, if you are eager to contribute to the have a look on the other issue or create your one. Closing this issue for now
