### ISSUE TITLE
Add Dark mode feature for stakeholders page

### ISSUE THREAD

**Issue by Harshdev098** [Harshdev098/Research-Nexas#8]
Add a dark mode button in stakeholders main page or on their profile page wherever its suitable 

![Screenshot from 2024-10-01 12-30-02](https://github.com/user-attachments/assets/44482c6e-6375-4c89-81b5-619d45fb2cff)

Will prefer to add a single button in profile page to toggle dark mode in both profile page and their main page

**Comment by NEGRAH-S** [comment]
@Harshdev098  , I am one of the mentor for this repo. I hope u made the PR for GSSoC extended 2024 . Will add required tag to issue and then review your PR .

**Comment by Harshdev098** [comment]
Sure, will grant the access, but can you share the selected mentor list I didn't found it

**Comment by NEGRAH-S** [comment]
@Harshdev098  here is link of doc you can have a look.
https://docs.google.com/spreadsheets/d/1fNNXgLIqSfywHqFe7nVSHgm7FhaxAKi-acOfXjtDv_M/edit?gid=0#gid=0

**Comment by Harshdev098** [comment]
Have added you as a collaborator @NEGRAH-S

**Comment by ash-k121** [comment]
Please assign this issue to me 
Name-Ashmeet Kaur uner gssoc -ext 2024

**Comment by ash-k121** [comment]
I have added the dark mode feature

**Comment by ash-k121** [comment]
Please add level  and hackobterfest label
