### ISSUE TITLE
Adding Feature of About Us

### ISSUE THREAD

**Issue by tanya-soni-git** [Harshdev098/Research-Nexas#84]
in profile section about us section is not available, I would like to add this section.

**Comment by SaanyaGarg5** [comment]
you can assign me this task... under gsso-ext and hacktoberfest and level 3 label..

**Comment by ambrishgoswami** [comment]
in profile section about us section is not available, I would like to add this section.

**Comment by 2027Anamika** [comment]
I want to add features , achievement , information, update etc in about us sections . please assign this task to me its my humble request @Harshdev098

**Comment by Harshdev098** [comment]
Someone has already raised a pr on that
