### ISSUE TITLE
FEATURE : Edit option in Profile for student

### ISSUE THREAD

**Issue by ygowthamr** [Harshdev098/Research-Nexas#89]
**What the feature does:** 

1 . This feature enables user to edit his profile information like name, email, collage name, etc in student dashboard of this app

**Images for reference:** 

1 . Edit profile page image
![image](https://github.com/user-attachments/assets/92286657-cf1d-4c1c-b970-dcbca3c1c1c9)

@Harshdev098 
Pls assign me this issue

**Give me labels like gssoc-extd,hacktoberfest,level3,etc**

**Comment by Harshdev098** [comment]
Are you gonna trying to make an endpoint to edit the profile @ygowthamr

**Comment by ygowthamr** [comment]
I want to give a feature for student to update his name, email and other details in student dashboard.

@Harshdev098
